language: node_js
os: linux
node_js:
  - 10.16.0

before-deploy:
  - git tag v0.0.1

deploy:
  provider: releases
  skip_cleanup: true
  keep_history: true
  api_key:
    secure: ${GITHUB_TOKEN}
  on:
    branch: master

branchs:
  only:
    - master
cache:
  directories:
    - node_modules
install:
  - npm install
scripts:
  - npm test
