language: node_js
os: linux
node_js:
  - 10.16.0

deploy:
  provider: releases
  skip_cleanup: true
  keep_history: true
  # github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  api_key:
    secure: ${GH_TOKEN}
  on:
    branch: master

branchs:
  only:
    - master
cache:
  directories:
    - node_modules
install:
  - npm install
scripts:
  - npm test
